### ISSUE TITLE
python3? works fine!

### ISSUE THREAD

**Issue by speculatrix** [ebrehault/superformatter#6]
ignore me, I was wrong. sorry.

**Comment by ebrehault** [comment]
This tool is more a demo than a real thing (don't use it it prod by the way).
I guess the Py3 upgrade would not be too hard. Go ahead if you want, I'll be happy to merge the PR :)

**Comment by speculatrix** [comment]
actually, I think I'm just using it wrong. I re-cloned the git repo and used your test code exactly as-is, specifying python3 when running and it worked fine. sorry.

**Comment by speculatrix** [comment]
ok, I had some stray curly brackets { in the input template which I'd missed. 
I changed the { .. } to {{ .. }} and it works.

many apologies.
